name: nodejs microservices CI/CD Pipeline

on:
  push:
    branches:
      - main          # Trigger workflow on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [16.x]

    #env:
     # PROJECT_PATH: /nodejs_shopping

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}    

      - name: Build products Backend with NPM
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MSG_QUEUE_URL: ${{ secrets.MSG_QUEUE_URL }}
          EXCHANGE_NAME: ${{ secrets.EXCHANGE_NAME }}
          PORT: ${{ secrets.PORT_PRODUCTS }} 
        run: |  
          cd nodejs_microservice_backend/products 
          npm ci          
          docker build -t ${{ secrets.EXCHANGE_NAME }}:${{ github.sha }} .

      - name: Build Frontend with NPM
        working-directory: ./shopping_app_frontend
        run: |
          #cd shopping_app_frontend
          npm ci
          npm run build
      
      - name: Build Frontend with NPM
        run: |
          echo "Finished"
